version: '2.1'
services:
  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    links:
      - scrapoxy
      - splash
      - database
    env_file:
      - crawler/scrapy.env
      - crawler/scrapy.secrets.env
    hostname: scrapy
    volumes:
      - ./data/logs:/usr/src/app/logs
      - ./data/share:/tmp/share
    network_mode: bridge

  metabase:
    image: metabase/metabase:v0.27.2
    env_file:
      - metabase/metabase.env
      - metabase/metabase.secrets.env
    links:
      - database
    ports:
      - "49302:3000"
    network_mode: bridge

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    env_file:
      - superset/superset.env
      - superset/superset.secrets.env
    ports:
      - "49303:8088"
    links:
      - database
      - redis
    hostname: superset
    network_mode: "bridge"
    volumes:
      - ./data/share:/tmp/share
      
  redis:
    image: redis
    restart: always
    network_mode: bridge

  splash:
    image: scrapinghub/splash:latest
    expose:
      - 8050
      - 5023
    links:
      - scrapoxy
    network_mode: bridge

  scrapoxy:
    build:
      context: ./scrapoxy
      dockerfile: Dockerfile
    env_file:
      - scrapoxy/scrapoxy.env
      - scrapoxy/scrapoxy.secrets.env
    ports:
      - "49301:8889"
    expose:
      - 8888
      - 8889
    network_mode: bridge

  database:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./data/database:/var/lib/postgresql/data/pgdata
      - ./data/share:/tmp/share
    env_file:
      - db/database.env
      - db/database.secrets.env
    network_mode: bridge