version: '2.1'
services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile-crawler
    links:
    - scrapoxy
    - database
    env_file:
    - crawler/scrapy.env
    - crawler/scrapy.secrets.env
    hostname: scrapy
    volumes:
      - ./data/logs:/usr/src/app/logs

  scrapoxy:
    image: fabienvauchelles/scrapoxy
    env_file:
    - crawler/scrapoxy.env
    - crawler/scrapoxy.secrets.env
    ports:
    - "49301:8889"
    expose:
    - 8888
    - 8889

  database:
    build:
      context: .
      dockerfile: Dockerfile-db
    volumes:
      - ./data/database:/var/lib/postgresql/data/pgdata
    env_file:
    - db/database.env
    - db/database.secrets.env